= Kotlin microservices

[IMPORTANT]
====
Tested with: 

* Maven 3.5.0
* Docker version 17.03.1-ce
* docker-compose version 1.11.2
====

== Running services

* Package apps:
+
[source,bash]
.execute in `kotlin-user-service`
$ mvn clean package
+
[source,bash]
.execute in `kotlin-api-gateway`
$ mvn clean package

* Start services
+
[source,bash]
.execute in project root
$ docker-compose up --build -d

* Sample user create request
+
[source,bash]
.execute in shell
http -h POST http://localhost:8080/users/ 'Content-Type: application/json' email=john@doe.com name=John lastname=Doe
+
[source]
.response
HTTP/1.1 201
Date: Thu, 25 May 2017 10:12:17 GMT
Location: http://localhost:8080/users/5926ae01410df8000740da9a
Transfer-Encoding: chunked
X-Application-Context: application

* Sample get user request
+
[source,bash]
.execute in shell
http :8080/users/5926ae01410df8000740da9a
+
[source]
.response
HTTP/1.1 200
Content-Type: application/json;charset=UTF-8
Date: Thu, 25 May 2017 10:12:43 GMT
Transfer-Encoding: chunked
X-Application-Context: application
{
    "email": "john@doe.com",
    "lastname": "Doe",
    "name": "John"
}